# Describes the format for available Dahua services

set_infrared_mode:
  name: Set Infrared Mode on Dahua Camera
  description: Set the infrared light settings on a Dahua camera
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    mode:
      description: "The infrared mode: Auto, On, Off"
      example: "Auto"
      default: "Auto"
      selector:
        select:
          options:
            - "Auto"
            - "On"
            - "Auto"
    brightness:
      description: The infrared brightness, from 0 to 100 inclusive. 100 is the brightest
      example: 100
      default: 100
      selector:
        number:
          min: 0
          max: 100
          step: 1
          mode: slider


set_video_profile_mode:
  name: Set Dahua Video Profile Mode To Day or Night
  description: Sets the video profile mode to day or night
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    mode:
      description: "The profile: Day, Night"
      example: "Day"
      selector:
        select:
          options:
            - "Day"
            - "Night"


enable_channel_title:
  name: Enable Channel Title Overlay
  description: Enables or disable the channel title video overaly
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    enabled:
      name: Enabled
      description: "If the overlay is enabled or not"
      example: true
      required: true
      default: true
      selector:
        boolean:


enable_time_overlay:
  name: Enable Channel Time Overlay
  description: Enables or disable the channel time video overaly
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    enabled:
      name: Enabled
      description: "If the overlay is enabled or not"
      example: true
      required: true
      default: true
      selector:
        boolean:


enable_text_overlay:
  name: Enable Channel Text Overlay
  description: Enables or disable the channel text video overaly
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    group:
      name: Group
      description: "Multiple text overlay groups can exist. The default 1 should be used in most cases"
      example: 1
      required: true
      default: 1
      selector:
        number:
          mode: box
          min: 0
          max: 100
    enabled:
      name: Enabled
      description: "If the overlay is enabled or not"
      example: true
      required: true
      default: false
      selector:
        boolean:


enable_custom_overlay:
  name: Enable Channel Custom Text Overlay
  description: Enables or disable the channel custom text video overaly
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    group:
      name: Group
      description: "Multiple custom text groups can exist. The default 0 should be used in most cases"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    enabled:
      name: Enabled
      description: "If the overlay is enabled or not"
      example: true
      required: true
      default: false
      selector:
        boolean:

set_custom_overlay:
  name: Set Custom Text Overlay
  description: Sets a custom text overlay on the video
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    group:
      name: Group
      description: "Multiple custom text groups can exist. The default 0 should be used in most cases"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    text1:
      name: Text 1
      description: "Custom overlay 1"
      example: "Text 1"
      required: false
      default: ""
      selector:
        text:
    text2:
      name: Text 2
      description: "Custom overlay 2"
      example: "Text 2"
      required: false
      default: ""
      selector:
        text:


set_channel_title:
  name: Sets Channel Title
  description: Sets a title on the video
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    text1:
      name: Text 1
      description: "The first title"
      example: "Front Porch"
      required: false
      default: ""
      selector:
        text:
    text2:
      name: Text 2
      description: "The second title"
      example: "House"
      required: false
      default: ""
      selector:
        text:


set_text_overlay:
  name: Set text overlay
  description: Sets a text overlay on the video
  target:
    entity:
      integration: dahua
      domain: camera
  fields:
    channel:
      name: Channel
      description: "The camera channel index. Typically 0"
      example: 0
      required: true
      default: 0
      selector:
        number:
          mode: box
          min: 0
          max: 100
    group:
      name: Group
      description: "Multiple custom text groups can exist. The default 1 should be used in most cases"
      example: 1
      required: true
      default: 1
      selector:
        number:
          mode: box
          min: 0
          max: 100
    text1:
      name: Text 1
      description: "Text overlay 1"
      example: "Text 1"
      required: false
      default: ""
      selector:
        text:
    text2:
      name: Text 2
      description: "Text overlay 2"
      example: "Text 2"
      required: false
      default: ""
      selector:
        text:
    text3:
      name: Text 3
      description: "Text overlay 3"
      example: "Text 3"
      required: false
      default: ""
      selector:
        text:
    text4:
      name: Text 4
      description: "Text overlay 4"
      example: "Text 4"
      required: false
      default: ""
      selector:
        text:
